import "./globals.css";
import { Inter } from "next/font/google";
import { WWProvider } from "../context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WiseWords",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <WWProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </WWProvider>
  );
}
